#!/usr/bin/env ruby
#
# This is a fake cucumber implementation used to test `cucumber-pretty`.
# It expects a single argument (a `testdata/*.feature` file) and will output
# JSON events to be consumed by `cucumber-pretty`.
#
require 'json'
feature_file = ARGV[0]
puts({
  event: "FeatureSourceRead",
  location: feature_file,
  source: File.open(feature_file, 'r:utf-8').read
}.to_json)
puts File.open(feature_file.gsub(/\.feature/, '.json'), 'r:utf-8').read
